/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EX9_SERVER_H_RPCGEN
#define _EX9_SERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define REMOTE_PROG_SKELETON 99
#define MESSAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IS_VALID_ID 1
extern  int * is_valid_id_1(char **, CLIENT *);
extern  int * is_valid_id_1_svc(char **, struct svc_req *);
#define ESTIMATE_PI 2
extern  double * estimate_pi_1(int *, CLIENT *);
extern  double * estimate_pi_1_svc(int *, struct svc_req *);
extern int remote_prog_skeleton_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IS_VALID_ID 1
extern  int * is_valid_id_1();
extern  int * is_valid_id_1_svc();
#define ESTIMATE_PI 2
extern  double * estimate_pi_1();
extern  double * estimate_pi_1_svc();
extern int remote_prog_skeleton_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EX9_SERVER_H_RPCGEN */
