ex1a:		mem.o main.o shell.o
			gcc mem.o shell.o main.o -o	ex1a

#ex1b:		mem.o main.o shell.o ex3b.o
#			gcc mem.o shell.o main.o -o	ex1b

#ex3b:		ex3b.c ex3b.h
#			gcc -Wall -c ex3b.c

shell.o:	shell.c shell.h
			gcc -Wall -c shell.c

mem.o:		mem.c mem.h
			gcc -Wall -c mem.c 

main.o:		main.c
			gcc -Wall -c main.c
		
		
